### ISSUE TITLE
Refresh gradle project configuration in build.gradle

### ISSUE THREAD

**Issue by amatiushkin** [intuit/Traverser#13]
Current version of traverser is using deprecated way to [declare dependencies](https://docs.gradle.org/current/userguide/declaring_dependencies.html), which uses older `testCompile` instead of `testImplementation`.

Most likely there are other features, which can be used from latest Gradle 6.x version.

`build.gradle` needs to be updated.

**Comment by samiur98** [comment]
Hi @amatiushkin I would like to help with the issue and work on this specific problem.

**Comment by samiur98** [comment]
Hello @amatiushkin I addressed the issue and made a PR
